title: Fontasia
description: A blog exploring the typography of Disney Pixar films
header_text: Fontasia
footer_text: Copyright 2020 Anna Gray
header_feature_image: ../uploads/fontasia-2.jpg
bannerheight: 20vmax
logo: ../uploads/aa-mouse.png
favicon: ../uploads/aa-mouse.png
gridlayout: false
fixednavbar: false
upzoom: true
