title: Fontasia
description: A blog exploring the typography of Disney Pixar films
header_text: ""
footer_text: Copyright 2020 Anna Gray
header_feature_image: ../uploads/fontasia-2.png
bannerheight: 20vmax
logo: ../uploads/mm.jpg
favicon: ../uploads/aa-mouse.png
gridlayout: false
fixednavbar: false
upzoom: true
