title: The Typography of Disney Pixar
description: A blog exploring the typography of Disney Pixar films
header_text: ""
footer_text: Copyright 2020 Anna Gray
header_feature_image: ../uploads/png-format.png
bannerheight: 20vmax
logo: ../uploads/logo-transpaernt.png
favicon: ../uploads/aa-mouse.png
gridlayout: false
fixednavbar: false
upzoom: true
items:
  - name: About Me
    siteurl: /aboutme
    tab: true
