title: Fontasia
description: A blog exploring the typography of Disney and Pixar
header_text: Fontasia
footer_text: Copyright 2020 Anna Gray
header_feature_image: ../uploads/aa-disney.jpg
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
